analyzer:
  errors:
    use_build_context_synchronously: ignore
    invalid_annotation_target: ignore
    deprecated_member_use: ignore
    must_be_immutable: ignore
    depend_on_referenced_packages: ignore
    unused_element_parameter: ignore

include: package:flutter_lints/flutter.yaml

linter:

  rules:
    prefer_relative_imports: true