import 'package:flutter/material.dart';

import '../function/app_size.dart';
import '../widget/widget_loading.dart';

class LoadingContents extends StatefulWidget {
  const LoadingContents({super.key});

  @override
  State<LoadingContents> createState() => _LoadingStateAbouUs();
}

class _LoadingStateAbouUs extends State<LoadingContents> {
  @override
  Widget build(BuildContext context) {
    return Column(
      mainAxisAlignment: MainAxisAlignment.start,
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        WidgetLoading(width: AppSize(context).width * 0.4),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.4),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.4),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.4),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.4),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.4),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.4),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.4),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.4),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.4),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
        SizedBox(height: AppSize(context).height * 0.01),
        WidgetLoading(width: AppSize(context).width * 0.9),
      ],
    );
  }
}
