// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0cymu6Jg3F6YemkAoOSudmYKJkV7L7XI',
    appId: '1:167167966746:android:d458f84eac92754b265ba3',
    messagingSenderId: '167167966746',
    projectId: 'wefix-1b290',
    storageBucket: 'wefix-1b290.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNtqj4MSmuBeGoU6yAVa-uX-J8Wx6_eXA',
    appId: '1:167167966746:ios:1baf9748c3714239265ba3',
    messagingSenderId: '167167966746',
    projectId: 'wefix-1b290',
    storageBucket: 'wefix-1b290.firebasestorage.app',
    androidClientId: '167167966746-00phnkj2k1n7992biiq3p31lpnarrgn8.apps.googleusercontent.com',
    iosClientId: '167167966746-e3al3bscnrri29qcee1li4mov37f0ehf.apps.googleusercontent.com',
    iosBundleId: 'com.tender.wefixsp.app',
  );

}